### ISSUE TITLE
setting up

### ISSUE THREAD

**Issue by steffenheyne** [anuprulez/interactionsviz#1]
Hi,
thanks for working on this project. I got the server running etc, but I can't see much!? Is this the current status or do I something wrong!?

**Comment by steffenheyne** [comment]
![image](https://user-images.githubusercontent.com/10652658/32053469-c0d281a0-ba5b-11e7-8544-f95e84a4cf03.png)

that's what I can see

**Comment by anuprulez** [comment]
Hi Steffen,

Thanks for using it. What you see is right. This screen shows the common (RNA-RNA) interactions among the selected files from the left panel. In this case, there is only one and all the interactions in this file are being shown.

An example gif:

![1](https://user-images.githubusercontent.com/3022518/32056782-d963c724-ba65-11e7-8779-b243b81787a7.gif)

Further, there is another screen which opens when any file is clicked. This screen shows interactions for the selected file. There are other features namely search, filter, export and summary.

An example gif:

![2](https://user-images.githubusercontent.com/3022518/32056836-f82c8c90-ba65-11e7-9281-9c345f8cee35.gif)

Please let me know if any other clarification is required. Thank you.

**Comment by steffenheyne** [comment]
Thanks, it works now after solving same package issues with Pavan. The basic problem was a mixture of pip and conda installed packages. conda list showed correct version, but the python found an older version in my ~/.local/lib/... directory. After uninstalling my local version,  the correct (conda) version was used.

The result is quite nice already. Maybe here and there some improvement on the user experience like filtering etc.
